use std::path::Path;

use serde_json::{json, Value};
use tokio::fs;

use crate::error::AppResult;
use crate::models::ShimModel;

const PLAN_TIERS: [&str; 6] = ["free", "plus", "pro", "team", "business", "enterprise"];

pub async fn write_catalog(models: &[ShimModel], path: &Path, include_chatgpt: bool) -> AppResult<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).await?;
    }
    let mut entries = Vec::new();
    if include_chatgpt {
        entries.push(chatgpt_passthrough_entry());
    }
    entries.extend(models.iter().map(catalog_entry));
    let payload = json!({"models": entries});
    fs::write(path, format!("{}\n", serde_json::to_string_pretty(&payload)?)).await?;
    Ok(())
}

pub async fn write_generated_config(
    models: &[ShimModel],
    path: &Path,
    catalog_path: &Path,
    port: u16,
    include_chatgpt: bool,
) -> AppResult<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).await?;
    }
    let default_slug = crate::models::default_model_slug(models, include_chatgpt);
    let text = format!(
        r#"# Generated by codex-shim. This file is opt-in and is not ~/.codex/config.toml.
model = "{}"
model_provider = "codex_shim"
model_catalog_json = "{}"

[model_providers.codex_shim]
name = "Codex Shim"
base_url = "http://127.0.0.1:{port}/v1"
wire_api = "responses"
experimental_bearer_token = "dummy"
request_max_retries = 3
stream_max_retries = 3
stream_idle_timeout_ms = 600000
"#,
        toml_escape(&default_slug),
        toml_escape(&catalog_path.display().to_string()),
    );
    fs::write(path, text).await?;
    Ok(())
}

fn catalog_entry(model: &ShimModel) -> Value {
    let context = model.max_context_limit.unwrap_or_else(|| default_context(model));
    let compact = 8_000.max((context as f64 * 0.8) as i64);
    let truncation = 64_000.min(8_000.max((context as f64 * 0.32) as i64));
    let supports_reasoning = supports_reasoning_summaries(model);
    json!({
        "slug": model.slug,
        "display_name": model.display_name,
        "description": format!("{} via local Codex shim.", model.display_name),
        "context_window": context,
        "max_context_window": context,
        "auto_compact_token_limit": compact,
        "truncation_policy": {"mode": "tokens", "limit": truncation},
        "default_reasoning_level": reasoning_effort(model),
        "supported_reasoning_levels": [
            {"effort": "low", "description": "Faster, lighter reasoning"},
            {"effort": "medium", "description": "Balanced speed and reasoning"},
            {"effort": "high", "description": "Deeper reasoning"},
            {"effort": "xhigh", "description": "Maximum reasoning where supported"}
        ],
        "default_reasoning_summary": if supports_reasoning { "auto" } else { "none" },
        "reasoning_summary_format": if supports_reasoning { "experimental" } else { "none" },
        "supports_reasoning_summaries": supports_reasoning,
        "default_verbosity": "low",
        "support_verbosity": false,
        "apply_patch_tool_type": "freeform",
        "web_search_tool_type": "text_and_image",
        "supports_search_tool": false,
        "supports_parallel_tool_calls": true,
        "experimental_supported_tools": [],
        "input_modalities": if model.no_image_support { vec!["text"] } else { vec!["text", "image"] },
        "supports_image_detail_original": !model.no_image_support,
        "shell_type": "shell_command",
        "visibility": "list",
        "minimal_client_version": "0.0.1",
        "supported_in_api": true,
        "availability_nux": Value::Null,
        "upgrade": Value::Null,
        "priority": 1.max(1000_i64.saturating_sub(model.index as i64)),
        "prefer_websockets": false,
        "available_in_plans": PLAN_TIERS,
        "base_instructions": "You are a coding agent running in Codex through a local BYOK shim.",
        "model_messages": {
            "instructions_template": "You are Codex running on {model_name} through a local all-model shim. Be a helpful, direct coding collaborator.",
            "instructions_variables": {"model_name": model.display_name}
        }
    })
}

fn chatgpt_passthrough_entry() -> Value {
    json!({
        "slug": "gpt-5.5",
        "display_name": "GPT-5.5",
        "description": "OpenAI GPT-5.5 - the default Codex model, routed through ChatGPT passthrough.",
        "context_window": 400000,
        "max_context_window": 400000,
        "auto_compact_token_limit": 320000,
        "truncation_policy": {"mode": "tokens", "limit": 64000},
        "default_reasoning_level": "medium",
        "supported_reasoning_levels": [
            {"effort": "minimal", "description": "Minimal reasoning"},
            {"effort": "low", "description": "Faster, lighter reasoning"},
            {"effort": "medium", "description": "Balanced"},
            {"effort": "high", "description": "Deeper reasoning"},
            {"effort": "xhigh", "description": "Maximum reasoning"}
        ],
        "default_reasoning_summary": "auto",
        "reasoning_summary_format": "experimental",
        "supports_reasoning_summaries": true,
        "default_verbosity": "medium",
        "support_verbosity": true,
        "apply_patch_tool_type": "freeform",
        "web_search_tool_type": "text_and_image",
        "supports_search_tool": true,
        "supports_parallel_tool_calls": true,
        "experimental_supported_tools": [],
        "input_modalities": ["text", "image"],
        "supports_image_detail_original": true,
        "shell_type": "shell_command",
        "visibility": "list",
        "minimal_client_version": "0.0.1",
        "supported_in_api": true,
        "availability_nux": Value::Null,
        "upgrade": Value::Null,
        "isDefault": true,
        "priority": 10000,
        "prefer_websockets": false,
        "available_in_plans": PLAN_TIERS,
        "base_instructions": "You are Codex, a coding agent powered by GPT-5.5.",
        "model_messages": {
            "instructions_template": "You are Codex, a coding agent powered by GPT-5.5.",
            "instructions_variables": {"model_name": "GPT-5.5"}
        }
    })
}

fn default_context(model: &ShimModel) -> i64 {
    let lower = format!("{} {}", model.model, model.display_name).to_lowercase();
    if lower.contains("claude") || lower.contains("deepseek") {
        200_000
    } else if lower.contains("gpt-5") {
        400_000
    } else if lower.contains("gemini") {
        1_000_000
    } else {
        128_000
    }
}

fn supports_reasoning_summaries(model: &ShimModel) -> bool {
    matches!(model.provider.as_str(), "deepseek" | "anthropic" | "minimax" | "dashscope" | "volcengine")
        || (model.provider == "moonshot" && model.model.starts_with("kimi-"))
}

fn reasoning_effort(model: &ShimModel) -> &'static str {
    let lower = model.display_name.to_lowercase();
    if lower.contains("xhigh") || lower.contains("x-high") {
        "xhigh"
    } else if lower.contains("high") {
        "high"
    } else if lower.contains("medium") {
        "medium"
    } else if lower.contains("low") {
        "low"
    } else {
        "medium"
    }
}

pub fn toml_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
